// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrvshzmypwjbnvditmbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhydnNoem15cHdqYm52ZGl0bWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzU2NDEsImV4cCI6MjA1NTgxMTY0MX0.3NTDxYftVEhM2oGPUd7hutfKIEcZmIo9OoY750PR2LU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);